services:
  db:
    image: postgres:16
    container_name: art_tracker_db
    environment:
      POSTGRES_DB: art_tracker
      POSTGRES_USER: artuser
      POSTGRES_PASSWORD: artpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: